[DEBUG] Host name:  gpu148.cluster.local
wandb: Starting wandb agent 🕵️
2025-01-27 01:18:49,465 - wandb.wandb_agent - INFO - Running runs: []
2025-01-27 01:18:49,696 - wandb.wandb_agent - INFO - Agent received command: run
2025-01-27 01:18:49,697 - wandb.wandb_agent - INFO - Agent starting run with config:
	batch_size: 4096
	d_layers: 1024
	data_path: ../../data/beijing
	dataset: beijing
	dim_t: 256
	dropout: 0.3
	log_interval: 50
	lr: 0.01
	n_layers: 5
	num_epochs: 4000
	seed: 42
	task_type: regression
2025-01-27 01:18:49,706 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python ../../main.py --batch_size=4096 --d_layers=1024 --data_path=../../data/beijing --dataset=beijing --dim_t=256 --dropout=0.3 --log_interval=50 --lr=0.01 --n_layers=5 --num_epochs=4000 --seed=42 --task_type=regression
2025-01-27 01:18:54,732 - wandb.wandb_agent - INFO - Running runs: ['zs6xq9qf']
/h/aguzmanc/miniforge3/envs/eval/lib/python3.11/site-packages/xgboost/core.py:265: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc 2.28+) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(
wandb: Currently logged in as: andresguzco. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.19.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.16.6
wandb: Run data is saved locally in /fs01/home/aguzmanc/xvfm/src/sweeps/wandb/run-20250127_011906-zs6xq9qf
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run dainty-sweep-11
wandb: ⭐️ View project at https://wandb.ai/andresguzco/XVFM
wandb: 🧹 View sweep at https://wandb.ai/andresguzco/XVFM/sweeps/q419mgxz
wandb: 🚀 View run at https://wandb.ai/andresguzco/XVFM/runs/zs6xq9qf
Number of parameters: 4634963
Training parameters: {'num_epochs': 4000, 'batch_size': 4096, 'lr': 0.01, 'integration_steps': 100, 'sigma': 0.01, 'dataset': 'beijing', 'log_interval': 50, 'seed': 42, 'results_dir': 'results', 'd_layers': 1024, 'n_layers': 5, 'dropout': 0.3, 'dim_t': 256, 'data_path': '../../data/beijing', 'task_type': 'regression', 'arch': [1024, 1024, 1024, 1024, 1024], 'num_feat': 6, 'classes': [5, 12, 31, 24, 4], 'd_in': 82}
Epoch [1/4000]: Loss: [78311903.5760]
Epoch [2/4000]: Loss: [129.6898]
Epoch [3/4000]: Loss: [103.7767]
Epoch [4/4000]: Loss: [72.7455]
Epoch [5/4000]: Loss: [70.0121]
Epoch [6/4000]: Loss: [64.8011]
Epoch [7/4000]: Loss: [63.8516]
Epoch [8/4000]: Loss: [57.1427]
Epoch [9/4000]: Loss: [57.4224]
Epoch [10/4000]: Loss: [59.1261]
Epoch [11/4000]: Loss: [55.6015]
Epoch [12/4000]: Loss: [53.9549]
Epoch [13/4000]: Loss: [54.4966]
Epoch [14/4000]: Loss: [54.7251]
Epoch [15/4000]: Loss: [52.5789]
Epoch [16/4000]: Loss: [54.0908]
Epoch [17/4000]: Loss: [53.8684]
Epoch [18/4000]: Loss: [54.3922]
Epoch [19/4000]: Loss: [52.9019]
Epoch [20/4000]: Loss: [56.8223]
Epoch [21/4000]: Loss: [53.1640]
Epoch [22/4000]: Loss: [52.5140]
Epoch [23/4000]: Loss: [54.4779]
Epoch [24/4000]: Loss: [54.2757]
Epoch [25/4000]: Loss: [51.8023]
Epoch [26/4000]: Loss: [52.0750]
Epoch [27/4000]: Loss: [54.5464]
Epoch [28/4000]: Loss: [54.2214]
Epoch [29/4000]: Loss: [53.1900]
Epoch [30/4000]: Loss: [54.6451]
Epoch [31/4000]: Loss: [53.7504]
Epoch [32/4000]: Loss: [53.8140]
Traceback (most recent call last):
  File "/fs01/home/aguzmanc/xvfm/src/sweeps/../../main.py", line 152, in <module>
    main(args)
  File "/fs01/home/aguzmanc/xvfm/src/sweeps/../../main.py", line 102, in main
    train(dataloader, test_data, flow_model, criterion, optimizer, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs01/home/aguzmanc/xvfm/src/sweeps/../../main.py", line 143, in train
    scores = evaluate(args, model, test_data, savedir, epoch + 1, flag, device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs01/home/aguzmanc/xvfm/xvfm/utils.py", line 57, in evaluate
    scores = get_performance(gen, test, args, plotting)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs01/home/aguzmanc/xvfm/xvfm/eval.py", line 85, in get_performance
    alpha, beta = get_quality(test_oh.cpu().numpy(), syn_oh.cpu().numpy())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs01/home/aguzmanc/xvfm/xvfm/eval.py", line 165, in get_quality
    qual_res = quality_evaluator.evaluate(rloader, sloader)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
    from contextlib import _GeneratorContextManager
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
    
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
    
  File "/h/aguzmanc/miniforge3/envs/eval/lib/python3.11/site-packages/synthcity/metrics/eval_statistical.py", line 60, in evaluate
    results = self._evaluate(X_gt, X_syn)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
    from contextlib import _GeneratorContextManager
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
    
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
    
  File "/h/aguzmanc/miniforge3/envs/eval/lib/python3.11/site-packages/synthcity/metrics/eval_statistical.py", line 720, in _evaluate
    oneclass_model = self._get_oneclass_model(X_)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/h/aguzmanc/miniforge3/envs/eval/lib/python3.11/site-packages/synthcity/metrics/core/metric.py", line 119, in _get_oneclass_model
    return load_from_file(cache_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/h/aguzmanc/miniforge3/envs/eval/lib/python3.11/site-packages/synthcity/utils/serialization.py", line 159, in load_from_file
    return cloudpickle.load(f)
           ^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
2025-01-27 01:21:32,033 - wandb.wandb_agent - INFO - Cleaning up finished run: zs6xq9qf
wandb: - 0.005 MB of 0.005 MB uploadedwandb: \ 0.005 MB of 0.028 MB uploadedwandb: | 0.028 MB of 0.028 MB uploadedwandb: 
wandb: Run history:
wandb:     alpha ▁▁▆██▇▇▆▆▆▆▆▆▆▆▅▆▆▆▆▆▅▅▅▆▅▆▆▆▆▆
wandb:      beta ▂▁▂▄▆▇▆▆▆▇▇▇▆▇▇▇▇▇▇▇▇▇▇▇▇█▇▇▇▇█
wandb: detection ▁▁▁▁▃▃▄▄▆▆▅▅▅▅▇▆▆▆▆▅▆▇▇▇█▅▆█▇▆█
wandb:      loss █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:   quality ▄▅▁▄▆▅▆▆▆▆▆▇▇▆█▇▇▇▇▇▇█▆▇▇▇▇██▇█
wandb:     shape ▂▃▁▃▅▄▆▆▆▆▅▆▆▆▇▆▆▆▆▆▇▇▆▇▇▆▆██▆█
wandb:     trend ██▁▅▆▅▆▆▆▆▆▇▇▇▆▇▇▆▆▇▆▆▆▆▇▆▆▇▇▇▆
wandb: 
wandb: Run summary:
wandb:     alpha 0.66858
wandb:      beta 0.27043
wandb: detection 0.61114
wandb:      loss 53.75044
wandb:   quality 0.83548
wandb:     shape 0.72849
wandb:     trend 0.94248
wandb: 
wandb: 🚀 View run dainty-sweep-11 at: https://wandb.ai/andresguzco/XVFM/runs/zs6xq9qf
wandb: ⭐️ View project at: https://wandb.ai/andresguzco/XVFM
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250127_011906-zs6xq9qf/logs
wandb: Terminating and syncing runs. Press ctrl-c to kill.
